# Tower Bloxx GBA - Butano 21.7.1 project
TARGET          := TowerBloxxGBA
BUILD           := build
LIBBUTANO       ?= ../../butano/butano
PYTHON          := python3
SOURCES         := src
INCLUDES        := include themes/christmas/include
DATA            :=
GRAPHICS        := graphics/gameplay graphics/ui graphics/backgrounds themes/christmas/graphics
AUDIO           := audio
AUDIOBACKEND    := maxmod
AUDIOTOOL       :=
DMGAUDIO        :=
DMGAUDIOBACKEND := null
ROMTITLE        := TOWER BLOXX
ROMCODE         := TBGA
USERFLAGS       :=
USERCXXFLAGS    :=
USERASFLAGS     :=
USERLDFLAGS     :=
USERLIBDIRS     :=
USERLIBS        :=
DEFAULTLIBS     :=
STACKTRACE      :=
USERBUILD       :=
EXTTOOL         :=

ifndef LIBBUTANOABS
export LIBBUTANOABS := $(realpath $(LIBBUTANO))
endif

include $(LIBBUTANOABS)/butano.mak
